# Generated by EzyTaskin CI on Sat May 17 09:56:35 UTC 2025.
# DO NOT EDIT.

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /App

ENV PATH="${PATH}:/root/.dotnet/tools"

# Download archive
ADD https://github.com/EzyTaskin/EzyTaskin_CI/releases/latest/download/EzyTaskin.tar.gz EzyTaskin.tar.gz
RUN tar -xzf EzyTaskin.tar.gz && rm -f EzyTaskin.tar.gz

# Load development secrets & copy for publish
RUN --mount=type=secret,id=appsettings_Secrets_json,dst=/etc/secrets/appsettings.Secrets.json     cp /etc/secrets/appsettings.Secrets.json .

# Synchronize database state
RUN ./DbUpdate

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /App
COPY --from=build-env /App .
ENTRYPOINT ["dotnet", "EzyTaskin.dll"]


