on:
    repository_dispatch:
        types: [EzyTaskin_Frontend]

concurrency:
  group: ${{ github.ref }}-${{ github.event.client_payload.after }}
  cancel-in-progress: true

jobs:
    ci:
        name: Unit Testing (Frontend)
        runs-on: ubuntu-latest
        env:
            REPO_FRONTEND: EzyTaskin_Frontend
            COMMIT: ${{ github.event.client_payload.after }}
        steps:
            - name: Setup Deploy Keys
              env:
                EZY_FRONTEND: ${{ secrets.EZY_FRONTEND }}
              run: |
                mkdir -p $HOME/.ssh

                echo "$EZY_FRONTEND" > $HOME/.ssh/ezy_frontend

                chmod 0600 $HOME/.ssh/ezy*

                echo "
                    Host frontend.ezytaskin
                        Hostname github.com
                        IdentityFile=$HOME/.ssh/ezy_frontend
                        User git
                " >> $HOME/.ssh/config

            - name: Export URLs
              run: |
                echo "URL_STATUS=${{ github.api_url }}/repos/${{ github.repository_owner }}/${{ env.REPO_FRONTEND }}/statuses/${{ env.COMMIT }}" >> $GITHUB_ENV
                echo "URL_WORKFLOW=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

            - name: Mark Commit Status
              run: |
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.EZY_GITHUB_TOKEN }}" \
                    ${{ env.URL_STATUS }} \
                    -d "
                    {
                        \"state\": \"pending\",
                        \"target_url\": \"${{ env.URL_WORKFLOW }}\",
                        \"description\": \"GitHub Actions workflow requested\",
                        \"context\": \"${{ github.repository }}\"
                    }
                    "

            - name: Build and Test
              run: |
                git clone git@frontend.ezytaskin:${{ github.repository_owner }}/${{ env.REPO_FRONTEND }}.git ${{ github.workspace }}/frontend

                pushd frontend
                npm install
                npm run build
                popd

            - name: Mark Commit Success
              if: success()
              run: |
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.EZY_GITHUB_TOKEN }}" \
                    ${{ env.URL_STATUS }} \
                    -d "
                    {
                        \"state\": \"success\",
                        \"target_url\": \"${{ env.URL_WORKFLOW }}\",
                        \"description\": \"GitHub Actions workflow succeeded\",
                        \"context\": \"${{ github.repository }}\"
                    }
                    "

            - name: Mark Commit Failure
              if: failure()
              run: |
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.EZY_GITHUB_TOKEN }}" \
                    ${{ env.URL_STATUS }} \
                    -d "
                    {
                        \"state\": \"failure\",
                        \"target_url\": \"${{ env.URL_WORKFLOW }}\",
                        \"description\": \"GitHub Actions workflow failed\",
                        \"context\": \"${{ github.repository }}\"
                    }
                    "
